#! /usr/bin/python

from subprocess import Popen, PIPE
import sys
import os
import xml.etree.ElementTree as ET

class BundleIdFromCommitHash:

    def modify_bundle_id(self, filename, suffix):
        tree = ET.parse(filename)
        plist = tree.getroot()
        bundle_identifier_element = self.get_bundle_identifier_element(plist)
        bundle_identifier_element.text = "%s.%s" % (bundle_identifier_element.text, suffix)
        tree.write(filename, encoding="utf-8")

    def get_bundle_identifier_element(self, plist):
        dict = plist.find("dict")
        just_past_bundle_id = False
        for child in dict:
            if just_past_bundle_id:
                return child
            just_past_bundle_id = (child.text == "CFBundleIdentifier")
        return None

obj = BundleIdFromCommitHash()
obj.modify_bundle_id (sys.argv[1], sys.argv[2])
